<Project Sdk="Microsoft.NET.Sdk">
	

	<PropertyGroup>
    <OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
		<RootNamespace>MiningOps</RootNamespace>
  </PropertyGroup>
	

	<ItemGroup>
	  <None Remove="Assets\barac.png" />
	  <None Remove="Assets\Electrical-Plans.jpg" />
	  <None Remove="Assets\ginder.png" />
	  <None Remove="Assets\HAM-CLUB.jpg" />
	  <None Remove="Assets\plumbing.jpg" />
	  <None Remove="Assets\ROCKBREAKER.jpg" />
	  <None Remove="Assets\sHANK.png" />
	  <None Remove="Assets\SHOVEL.jpg" />
	  <None Remove="Assets\sportcourt.jpg" />
	  <None Remove="Assets\thread.png" />
	  <None Remove="Assets\WHEELBARR.jpg" />
	</ItemGroup>
	


	

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.49.0" />
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.9" />
  </ItemGroup>
	<ItemGroup>
		<Folder Include="Utilities\" />
		<Folder Include="Data\" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Assets\barac.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\Electrical-Plans.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\ginder.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\HAM-CLUB.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\plumbing.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\ROCKBREAKER.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\sHANK.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\SHOVEL.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\sportcourt.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\thread.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Assets\WHEELBARR.jpg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>
